### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by carter-bailey** [TheHuddle/pr-practice#1]
Because why not?

**Comment by wrynegade** [comment]
don't forget to assign yourself to the issue! :)

**Comment by wrynegade** [comment]
Update: Github doesn't allow me to give you self-assign access; I will assign you :)

**Comment by wrynegade** [comment]
@tacocat01 any progress!? I'm excited to see your PR!

**Comment by carter-bailey** [comment]
@w0ryn its been put on the back burner until after finals but don't worry I've been thinking up some good ideas.
