### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by ghost** [TheHuddle/pr-practice#15]
I have a background in web dev and there is a ton of cool stuff javascript and js libraries can do!

**Comment by wrynegade** [comment]
#16 Is related; however, I'd rather give you full control over your own project. Let's include this as a git submodule for you submission!

**Comment by wrynegade** [comment]
1. Create your own repository where you can host this project
2. Create a new feature branch from the up-to-date main branch
3. Run the git submodule command below (replacing your appropriate target), and commit the new changes
4. Make a PR from that branch :)

```shell
# run this command in the pr-practice project root!
# Be sure to replace YOUR-DISCORD-HANDLE and YOUR.GIT/REPOSITORY appropriately

git submodule add --name YOUR-DISCORD-HANDLE -- https://YOUR.GIT/REPOSITORY hello-world/YOUR-DISCORD-HANDLE
```
